name: CICD Pipeline

on:
 push:
        branches:
            - main
            - 'feature/**'
        paths-ignore:
          #  - '.github/workflows/*'  
            - README.md 
jobs:
  code:
    uses: ./.github/workflows/code.yaml # this is how workflows is called
  build:
    needs: code
    uses: ./.github/workflows/build.yaml
  test:
    needs: build
    uses: ./.github/workflows/test.yaml
  deploy:
    needs: test
    uses: ./.github/workflows/deploy.yaml
